[package]
name = "simplex-cuda"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cust = { version = "0.3.2", optional = true }
tracing = "0.1.44"

[features]
cuda = ["cust"]

[dev-dependencies]
criterion = "0.8.1"
tracing-subscriber = "0.3.22"

# Aggressive optimization for benchmarks
[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1

[[bench]]
name = "flat_matrix"
harness = false

[[bench]]
name = "simplex"
harness = false

[[bench]]
name = "cpu_vs_gpu"
harness = false
